export const SET_WEATHER_SUMMARY = 'SET_WEATHER_SUMMARY';
export const SET_WEATHER_HOURLY = 'SET_WEATHER_HOURLY';
export const SET_WEATHER_FORECAST = 'SET_WEATHER_FORECAST';

export const SET_CITY = 'SET_CITY';
export const SET_TEMP_UNIT = 'SET_TEMP_UNIT';
